import clsx from 'clsx'
export interface ItemProps {
  name: string
  idx?: number
  fullName?: string
  description?: string
  indicatorName?: string
  indicatorIndex?: { idx1: number; idx2: number }
  strategyName?: string
  strategyIndex?: { idx1: number; idx2: number }
  action1?: (indicatorId, name, callback, strategId?) => void
  action2?: (indicatorId, buttonId, name, callback, strategId?) => void
}
export interface ItemsProps {
  category: string
  items: ItemProps[]
}
/**
 * Items definitions of Strategies
 */
export const StrategiesItems: ItemsProps[] = [
  {
    category: 'Momentum',
    items: [
      {
        name: 'awesomeOsc',
        fullName: 'awesomeOscillatorStrategy',
        description: `Awesome oscillator strategy,The awesomeOscillatorStrategy uses the ao values that are generated by the Awesome Oscillator indicator function to provide a SELL action when the ao is below zero, and a BUY action when ao is above zero.`,
        indicatorName: 'AO',
      },
      {
        name: 'Ichimoku',
        fullName: 'ichimokuCloudStrategy',
        description: `Ichimoku cloud strategy,The ichimokuCloudStrategy uses the ao values that are generated by the Ichimoku Cloud indicator function to provide a BUY action when the leadingSpanA is greather than leadingSpanB, and a SELL action when the leadingSpanA is less than leadingSpanB, and a HOLD action when leadingSpanA is equal to leadingSpanB.`,
        indicatorName: 'Ichimoku',
      },
      {
        name: 'RSI2',
        fullName: 'rsi2Strategy',
        description: `RSI 2. The rsi2Strategy uses the rsi values that are generated by the RSI 2 indicator function to provide a BUY action when 2-period RSI moves below 10, and a SELL action when the 2-period RSI moved above 90, and a HOLD action otherwise. `,
        indicatorName: 'RSI',
      },
      {
        name: 'Stoch',
        fullName: `StochasticOscillatorStrategy`,
        description: `The stochasticOscillatorStrategy uses the ao values that are generated by the Stochastic Oscillator indicator function to provide a BUY action when k and d are less than 20, a SELL action when the k and d are greather than 80, a HOLD action otherwise.`,
        indicatorName: 'Stoch',
      },
      {
        name: 'willRS',
        fullName: `williamRStrategy`,
        description: `The williamsRStrategy uses the wr values that are generated by the Williams R indicator function to provide a SELL action when the wr is below -20, and a BUY action when wr is above -80.`,
        indicatorName: 'willR',
      },
    ],
  },
  {
    category: 'Trend',
    items: [
      {
        name: 'APO',
        fullName: 'absolutePriceOscillatorStrategy',
        description: `The absolutePriceOscillatorStrategy uses the values that are generated by the Absolute Price Oscillator (APO) indicator to provide a BUY action when the AO is greather than zero, and SELL action when AO is less than zero, otherwise HOLD action.`,
        indicatorName: 'APO',
      },
      {
        name: 'Aroon',
        fullName: 'aroonStrategy',
        description: `The aroonStrategy uses the values that are generated by the Aroon Indicator to provide a BUY action when the up is greather than down, and SELL action when up is less than down, otherwise HOLD action.`,
        indicatorName: 'Aroon',
      },
      {
        name: 'BOP',
        fullName: 'balanceOfPowerStrategy',
        description: `The balanceOfPowerStrategy uses the values that are generated by the Balance of Power (BOP) indicator to provide a BUY action when the BOP is greather than zero, and SELL action when BOP is less than zero, otherwise HOLD action.`,
        indicatorName: `BOP`,
      },
      {
        name: 'CFO',
        fullName: 'chandeForecastOscillatorStrategy',
        description: `The chandeForecastOscillatorStrategy uses cfo values that are generated by the Chande Forecast Oscillator (CFO) indicator function to provide a BUY action when cfo is below zero, and SELL action when cfo is above zero.`,
        indicatorName: `CFO`,
      },
      {
        name: 'KDJ',
        fullName: 'kdjStrategy',
        description: `The kdjStrategy function uses the k, d, j values that are generated by the Random Index (KDJ) indicator function to provide a BUY action when k crosses above d and j. It is stronger when below 20%. Also the SELL action is when k crosses below d and j. It is strong when above 80%.`,
        indicatorName: 'KDJ',
      },
      {
        name: 'MACD',
        fullName: 'macdStrategy',
        description: `The macdStrategy uses the macd, and signal values that are generated by the Moving Average Convergence Divergence (MACD) indicator function to provide a BUY action when macd crosses above signal, and SELL action when macd crosses below signal.`,
        indicatorName: 'MACD',
      },
      {
        name: 'PSAR',
        fullName: 'parabolicSARStrategy',
        description: `The parabolicSARStrategy uses the values that are generated by the Parabolic SAR indicator function to provide a BUY action when the trend is FALLING, and SELL action when the trend is RISING, and HOLD action when the trend is STABLE.`,
        indicatorName: 'PSAR',
      },
      {
        name: 'typPRICE',
        fullName: 'typicalPriceStrategy',
        description: `The typicalPriceStrategy uses the values that are generated by the Typical Price indicator function to provide a BUY action when the value is greather than the previous value, and SELL action when the value is less than the previous value, and HOLD action when value is equal to the previous value.`,
        indicatorName: 'typPRICE',
      },
      {
        name: 'Vortex',
        fullName: '',
        description: `The vortexStrategy uses the values that are generated by the Vortex Indicator indicator function to provide a BUY action when the plusVi is greather than the minusVi, and SELL action when the plusVi is less than the minusVi, and HOLD action when the plusVi is equal to the minusVi.`,
        indicatorName: 'Vortex',
      },
      {
        name: 'VWMA',
        fullName: 'vwmaStrategy',
        description: `The vwmaStrategy function uses SMA and VWMA indicators to provide a BUY action when VWMA is above SMA, and a SELL signal when VWMA is below SMA, a HOLD signal otherwse.`,
        indicatorName: 'VWMA',
      },
    ],
  },
  {
    category: 'Volatility',
    items: [
      {
        name: 'AB',
        fullName: 'accelerationBandsTrategy',
        description: `The accelerationBandsStrategy uses the upperBand, and lowerBand values that are generated by the Acceleration Bands indicator function to provide a BUY action when closing is greather than or equals to upperBand, a SELL action otherwise.`,
        indicatorName: 'AB',
      },
      {
        name: 'BB',
        fullName: 'BollingerBandsStrategy',
        description: `The bollingerBandsStrategy uses the upperBand, and lowerBand values that are generated by the Bollinger Bands indicator function to provide a SELL action when the asset's closing is above the upperBand, and a BUY action when the asset's closing is below the lowerBand values, a HOLD action otherwise.`,
        indicatorName: 'BB',
      },
      {
        name: 'PO',
        fullName: '',
        description: `The projectionOscillatorStrategy uses po and spo values that are generated by the Projection Oscillator (PO) indicator function to provide a BUY action when po is above spo, and SELL action when po is below spo.`,
        indicatorName: 'PO',
      },
    ],
  },
  {
    category: 'Volume',
    items: [
      {
        name: 'CMF',
        fullName: 'chaikinMoneyFlowStrategy',
        description: `The chaikinMoneyFlowStrategy uses the cmf values that are generated by the Chaikin Money Flow (CMF) indicator function to provide a BUY action when cmf is less than zero, a SELL action when cmf is greather than zero, a HOLD action otherwise.`,
        indicatorName: 'CMF',
      },
      {
        name: 'EMV',
        fullName: 'easeOfMovementStrategy',
        description: `The easeOfMovementStrategy uses the emv values that are generated by the Ease of Movement (EMV) indicator function to provide a BUY action when emv is greather than zero, and a SELL action when emv is less than zero, a HOLD action otherwise.`,
        indicatorName: 'EMV',
      },
      {
        name: 'FI',
        fullName: 'forceIndex',
        description: `The forceIndexStrategy uses the fi values that are generated by the Force Index (FI) indicator function to provide a BUY action when fi is greather than zero, and a SELL action when fi is less than zero, a HOLD action otherwise.`,
        indicatorName: 'FI',
      },
      {
        name: 'MFI',
        fullName: 'moneyFlowIndexStrategy',
        description: `The moneyFlowIndexStrategy uses the mfi values that are generated by the Money Flow Index (MFI) indicator function to provide a SELL action when mfi is greather than or equal to 80, and a BUY action when mfi is less than or equal to 20.`,
        indicatorName: 'MFI',
      },
      {
        name: 'NVI',
        fullName: 'negativeVolumeIndexStrategy',
        description: `The negativeVolumeIndexStrategy uses the nvi values that are generated by the Negative Volume Index (NVI) indicator function to provide a BUY action when nvi is less than its 255-period EMA, and a SELL action when it is greather than its 255-period EMA, otherwise a HOLD action.`,
        indicatorName: 'NVI',
      },
      {
        name: 'VWAP',
        fullName: 'volumeWeightedAveragePriceStrategy',
        description: `The volumeWeightedAveragePriceStrategy uses the values that are generated by the Volume Weighted Average Price (VWAP) indicator function to provide a BUY action when the closing is above the VWAP, and a SELL action when the closing is below the VWAP, a HOLD action otherwise.`,
        indicatorName: 'VWAP',
      },
    ],
  },
]
/**
 * Items for Indicators
 */
export const IndicatorsItems: ItemsProps[] = [
  {
    category: 'Default',
    items: [
      {
        name: 'VOL',
        fullName: 'Volume',
        description:
          'Stock trading volume is the total number of shares, contracts, or units of a security traded between buyers and sellers during a specific period, typically a single trading day.',
      },
    ],
  },
  {
    category: 'Momentum',
    items: [
      {
        name: 'AO',
        fullName: 'awesomeOscillator',
        description: `<h3>Awesome Oscillator (AO)</h3> <p>it is a momentum indicator developed by Bill Williams that measures market trends by calculating the difference between a 34-period and a 5-period simple moving average (SMA) of median prices (high + low)/2. It displays as a histogram, where positive values indicate bullish momentum, negative values indicate bearish, and color changes (green/red) suggest potential reversals or trend strength.
<ul class="list-inside list-disc">
  <li>Median Price = ((Low + High) / 2)</li>
  <li>AO = 5-Period SMA - 34-Period SMA.</li>
</ul></p>`,
        strategyName: 'awesomeOsc',
      },
      {
        name: 'CMO',
        fullName: 'chaikinOscillator',
        description: `<h3>Chaikin Oscillator</h3> <p> It measures the momentum of the Accumulation/Distribution (A/D) using the Moving Average Convergence Divergence (MACD) formula. It takes the difference between fast and slow periods EMA of the A/D. Cross above the A/D line indicates bullish.
<ul class="list-disc list-inside">
  <li>CO = Ema(fastPeriod, AD) - Ema(slowPeriod, AD)</li>
</ul></p>`,
      },
      {
        name: 'Ichimoku',
        fullName: 'ichimokuCloud',
        description: `<h3>Ichimoku Cloud</h3> <p>Also known as Ichimoku Kinko Hyo, is a versatile indicator that defines support and resistence, identifies trend direction, gauges momentum, and provides trading signals.
<ul class="list-inside list-disc">
  <li>Tenkan-sen (Conversion Line) = (9-Period High + 9-Period Low) / 2</li>
  <li>Kijun-sen (Base Line) = (26-Period High + 26-Period Low) / 2</li>
  <li>Senkou Span A (Leading Span A) = (Conversion Line + Base Line) / 2 projected 26 periods in the future</li>
  <li>Senkou Span B (Leading Span B) = (52-Period High + 52-Period Low) / 2 projected 26 periods in the future</li>
  <li>Chikou Span (Lagging Span) = Closing plotted 26 periods in the past.</li>
</ul></p>`,
        strategyName: 'Ichimoku',
      },
      {
        name: 'PPO',
        fullName: 'percentagePriceOscillator',
        description: `<h3>Percentage Price Oscillator (PPO)</h3> <p>It is a momentum oscillator for the price. It is used to indicate the ups and downs based on the price. A breakout is confirmed when PPO is positive.
<ul class="list-inside list-disc">
  <li>PVO = ((EMA(fastPeriod, prices) - EMA(slowPeriod, prices)) / EMA(longPeriod, prices)) * 100,</li>
  <li>Signal = EMA(9, PVO)</li>
  <li>Histogram = PVO - Signal</li>
</ul></p>`,
      },
      {
        name: 'PVO',
        fullName: 'percentageVolumeOscillator',
        description: `<h3>Percentage Volume Oscillator (PVO)</h3> <p>It is a momentum oscillator for the volume. It is used to indicate the ups and downs based on the volume. A breakout is confirmed when PVO is positive.
<ul class="list-insdie list-disc">
  <li>PVO = ((EMA(fastPeriod, volumes) - EMA(slowPeriod, volumes)) / EMA(longPeriod, volumes)) * 100.</li>
  <li>Signal = EMA(9, PVO),</li>
  <li>Histogram = PVO - Signal</li>
</ul></p>`,
      },
      {
        name: 'ROC',
        fullName: 'priceRateOfChange',
        description: `<h3>Price Rate of Change (ROC)</h3><p>The Price Rate of Change (ROC) is a technical momentum oscillator that measures the percentage difference between the current price and the price (n) periods ago. It identifies trend speed, reversals, and overbought/oversold conditions, typically plotted around a zero line.
<ul class="list-inside list-disc">
  <li>ROC[i] = 0 when i < period,</li>>
  <li>ROC[i] = (close[i] / close[i-period] - 1) * 100 when i >= period</li>
</ul></p>`,
      },
      {
        name: 'RSI',
        fullName: 'relativeStrengthIndex',
        description: `<h3>Relative Strength Index (RSI)</h3>
        <p>It is a momentum indicator that measures the magnitude of recent price changes to evaluate overbought and oversold conditions using the given window period.
<ul class="list-inside list-disc">
  <li>RS = Average Gain / Average Loss,</li>
  <li>RSI = 100 - (100 / (1 + RS))</li>
</ul></p>`,
        strategyName: 'RSI2',
      },
      {
        name: 'Stoch',
        fullName: 'stochasticOscillator',
        description: `<h3>Stochastic Oscillator</h3><p>It is a momentum indicator that shows the location of the closing relative to high-low range over a set number of periods.
<ul class="list-insdie list-disc">
  <li>K = (Closing - Lowest Low) / (Highest High - Lowest Low) * 100</li>
  <li>D = 3-Period SMA of K</li>
</ul></p>`,
        strategyName: 'Stoch',
      },
      {
        name: 'willR',
        fullName: 'williamsR',
        description: `<h3>Williams R</h3><p>The Williams %R indicator, created by Larry Williams, is a momentum-based oscillator ranging from (0) to (-100) that measures overbought and oversold levels by comparing the closing price to the high-low range over a set period (typically (14) days). Readings above (-20) indicate overbought conditions, while readings below (-80) suggest oversold conditions.
<ul class="list-inside list-disc">
  <li>WR = (Highest High - Closing) / (Highest High - Lowest Low) * -100.</li>
</ul>
Buy when -80 and below. Sell when -20 and above.</p>`,
        strategyName: 'willRS',
      },
    ],
  },
  {
    category: 'Trend',
    items: [
      {
        name: 'APO',
        fullName: 'absolutePriceOscillator',
        description: `<h3>Absolute Price Oscillator (APO)</h3> <p>It calculates the technical indicator that is used to follow trends. APO crossing above zero indicates bullish, while crossing below zero indicates bearish. Positive value is upward trend, while negative value is downward trend.<br>
Fast = EMA(fastPeriod, values)</br>
Slow = EMA(slowPeriod, values)</br>
APO = Fast - Slow</p>`,
        strategyName: 'APO',
      },
      {
        name: 'Aroon',
        fullName: 'aroon',
        description: `<h3>Aroon Indicator</h3> <p>It is a technical indicator that is used to identify trend changes in the price of a stock, as well as the strength of that trend. It consists of two lines, Arron Up, and Aroon Down. The Aroon Up line measures the strength of the uptrend, and the Aroon Down measures the strength of the downtrend. When Aroon Up is above Aroon Down, it indicates bullish price, and when Aroon Down is above Aroon Up, it indicates bearish price.<br>
Aroon Up = ((25 - Period Since Last 25 Period High) / 25) * 100 <br>
Aroon Down = ((25 - Period Since Last 25 Period Low) / 25) * 100</p>`,
        strategyName: `Aroon`,
      },
      {
        name: 'BOP',
        fullName: 'balanceOfPower',
        description: `<h3>Balance of Power (BOP)</h3> <p>It calculates the strength of buying and selling pressure. Positive value indicates an upward trend, and negative value indicates a downward trend. Zero indicates a balance between the two.<br>
BOP = (Closing - Opening) / (High - Low)</p>`,
        strategyName: `BOP`,
      },
      {
        name: 'CFO',
        fullName: 'chandeForecastOscillator',
        description: `<h3>Chande Forecast Oscillator</h3><p>It was developed by Tushar Chande The Forecast Oscillator plots the percentage difference between the closing price and the n-period linear regression forecasted price. The oscillator is above zero when the forecast price is greater than the closing price and less than zero if it is below.<br>
R = Linreg(Closing)<br>
CFO = ((Closing - R) / Closing) * 100</p>`,
        strategyName: 'CFO',
      },
      {
        name: 'MCFO',
        fullName: 'movingChandeForecastOscillator',
        description: `<h3>Moving Chande Forecast Oscillator</h3><p>It calculates based on the given period. The Chande Forecast Oscillator developed by Tushar Chande The Forecast Oscillator plots the percentage difference between the closing price and the n-period linear regression forecasted price. The oscillator is above zero when the forecast price is greater than the closing price and less than zero if it is below.<br>
R = Linreg(Closing)<br>
CFO = ((Closing - R) / Closing) * 100</p>`,
      },
      {
        name: 'CCI',
        fullName: 'communityChangeIndex',
        description: `<h3>Community Channel Index (CCI)</h3><p> It is a momentum-based oscillator used to help determine when an investment vehicle is reaching a condition of being overbought or oversold.<br>
Moving Average = Sma(Period, Typical Price)<br>
Mean Deviation = Sma(Period, Abs(Typical Price - Moving Average))<br>
CMI = (Typical Price - Moving Average) / (0.015 * Mean Deviation)</p>`,
      },
      {
        name: 'DEMA',
        fullName: 'doubleExponentialMovingAverage',
        description: `Dema calculates the Double Exponential Moving Average (DEMA)/
DEMA = (2 * EMA(values)) - EMA(EMA(values))`,
      },
      {
        name: 'EMA',
        fullName: 'exponentialMovingAverage',
        description: `Exponential moving average (EMA).`,
      },
      {
        name: 'KDJ',
        fullName: 'randomIndex',
        description: `<h3>HDK</h3><p>The kdj function calculates the KDJ indicator, also known as the Random Index. KDJ is calculated similar to the Stochastic Oscillator with the difference of having the J line. It is used to analyze the trend and entry points.<br>
The K and D lines show if the asset is overbought when they crosses above 80%, and oversold when they crosses below 20%. The J line represents the divergence.<br>
RSV = ((Closing - Min(Low, rPeriod)) / (Max(High, rPeriod) - Min(Low, rPeriod))) * 100<br>
K = Sma(RSV, kPeriod)<br>
D = Sma(K, dPeriod)<br>
J = (3 * K) - (2 * D)</p>`,
        strategyName: 'KDJ',
      },
      {
        name: 'MI',
        fullName: 'massIndex',
        description: `<h3>Mass Index (MI)</h3><p>It uses the high-low range to identify trend reversals based on range expansions.<br>
Singe EMA = EMA(9, Highs - Lows)<br>
Double EMA = EMA(9, Single EMA)<br>
Ratio = Single EMA / Double EMA<br>
MI = Sum(25, Ratio)</p>`,
      },
      {
        name: 'MACD',
        fullName: 'movingAverageConvergenceDivergence',
        description: `<h3>Moving Average Convergence Divergence (MACD)</h3><p>The Moving Average Convergence Divergence (MACD) is a popular trend-following momentum indicator used in technical analysis to measure the relationship between two exponential moving averages (EMAs) of a security’s price. It helps identify trend direction, strength, and potential entry/exit points by showing changes in momentum, typically calculated as the 12-period EMA minus the 26-period EMA.<br>
MACD = 12-Period EMA - 26-Period EMA.<br>
 Signal = 9-Period EMA of MACD.</p>`,
        strategyName: 'MACD',
      },
      {
        name: 'MMAX',
        fullName: 'movingMax',
        description: `Moving max for the given period.`,
      },
      {
        name: 'MMIN',
        fullName: 'movingMin',
        description: `Moving min for the given period.`,
      },
      {
        name: 'MSUM',
        fullName: 'movingSum',
        description: `Moving sum for the given period.`,
      },
      {
        name: 'PSAR',
        fullName: 'parabolicSAR',
        description: `<h3>Parabolic SAR</h3><p>It is a popular technical indicator for identifying the trend and as a trailing stop.<br>
SAR = PSAR[i - 1] - ((PSAR[i - 1] - EP) * AF)<br>
If the trend is Falling:<br>
 - PSAR is the maximum of PSAR or the previous two high values.<br>
 - If the current high is greather than or equals to PSAR, use EP.<br>
If the trend is Rising:<br>
 - PSAR is the minimum of PSAR or the previous two low values.<br>
 - If the current low is less than or equals to PSAR, use EP.<br>
If PSAR is greater than the closing, trend is falling, and the EP is set to the minimum of EP or the low.<br>
If PSAR is lower than or equals to the closing, trend is rising, and the EP is set to the maximum of EP or the high.<br>
If the trend is the same, and AF is less than 0.20, increment it by 0.02.<br>
If the trend is not the same, set AF to 0.02.</p>`,
        strategyName: 'PSAR',
      },
      {
        name: 'QSTICK',
        fullName: 'QSTICK',
        description: `The Qstick function calculates the ratio of recent up and down bars.

QS = Sma(Closing - Opening)`,
      },
      {
        name: 'RMA',
        fullName: 'rollingMovingAverage',
        description: `Rolling moving average (RMA).

R[0] to R[p-1] is SMA(values)
R[p] and after is R[i] = ((R[i-1]*(p-1)) + v[i]) / p`,
      },
      {
        name: 'SMA',
        fullName: 'simpleMovingAverage',
        description: `A Simple Moving Average (SMA) is a technical indicator that calculates the average price of an asset over a specific number of periods (e.g., days, hours) by summing closing prices and dividing by that number. It smooths out price volatility to identify trends, with equal weight assigned to all data points.  `,
      },
      {
        name: 'typPRICE',
        fullName: 'typical Price',
        description: `The typicalPrice function calculates another approximation of average price for each period and can be used as a filter for moving average systems`,
        strategyName: 'typPRICE',
      },
      {
        name: 'Vortex',
        fullName: '',
        description: `The vortex function provides two oscillators that capture positive and negative trend movement. A bullish signal triggers when the positive trend indicator crosses above the negative trend indicator or a key level. A bearish signal triggers when the negative trend indicator crosses above the positive trend indicator or a key level.`,
        strategyName: 'Vortex',
      },
      {
        name: 'VWMA',
        fullName: 'Volume Weighted Moving Average',
        description: `The vwma function calculates the Volume Weighted Moving Average (VWMA) averaging the price data with an emphasis on volume, meaning areas with higher volume will have a greater weight.`,
        strategyName: 'VWMA',
      },
    ],
  },
  {
    category: 'Volatility',
    items: [
      {
        name: 'AB',
        fullName: 'accelulationBands',
        description: `The accelerationBands plots upper and lower envelope bands around a simple moving average.

Upper Band = SMA(High * (1 + 4 * (High - Low) / (High + Low)))
Middle Band = SMA(Closing)
Lower Band = SMA(Low * (1 + 4 * (High - Low) / (High + Low)))`,
        strategyName: 'AB',
      },
      {
        name: 'ATR',
        fullName: 'averageTrueRange',
        description: `The atr function calculates a technical analysis indicator that measures market volatility by decomposing the entire range of stock prices for that period.

TR = Max((High - Low), (High - Closing), (Closing - Low))
ATR = 14-Period SMA TR`,
      },
      {
        name: 'BB',
        fullName: 'Bollinger Bands',
        description: `The bollingerBands function calculates the bollinger bands, middle band, upper band, lower band, provides identification of when a stock is oversold or overbought.

Middle Band = 20-Period SMA.
Upper Band = 20-Period SMA + 2 (20-Period Std)
Lower Band = 20-Period SMA - 2 (20-Period Std)`,
        strategyName: 'BB',
      },
      {
        name: 'BBW',
        fullName: 'Bollinger Bands Width',
        description: `The bollingerBandsWidth function measures the percentage difference between the upper band and the lower band. It decreases as Bollinger Bands narrows and increases as Bollinger Bands widens. During a period of rising price volatility the band width widens, and during a period of low market volatility band width contracts.

Band Width = (Upper Band - Lower Band) / Middle Band`,
      },
      {
        name: 'CE',
        fullName: 'Chandelier Exit',
        description: `The chandelierExit function sets a trailing stop-loss based on the Average True Value (ATR).

Chandelier Exit Long = 22-Period SMA High - ATR(22) * 3
Chandelier Exit Short = 22-Period SMA Low + ATR(22) * 3`,
      },
      {
        name: 'DC',
        fullName: `Donchian Channel`,
        description: `The donchianChannel calculates three lines generated by moving average calculations that comprise an indicator formed by upper and lower bands around a midrange or median band. The upper band marks the highest price of an asset while the lower band marks the lowest price of an asset, and the area between the upper and lower bands represents the Donchian Channel.

Upper Channel = Mmax(closings, { period })
Lower Channel = Mmin(closings, { period })
Middle Channel = (Upper Channel + Lower Channel) / 2`,
      },
      {
        name: 'KC',
        fullName: 'Keltner Channel',
        description: `The keltnerChannel provides volatility-based bands that are placed on either side of an asset's price and can aid in determining the direction of a trend.

Middle Line = EMA(period, closings)
Upper Band = EMA(period, closings) + 2 * ATR(period, highs, lows, closings)
Lower Band = EMA(period, closings) - 2 * ATR(period, highs, lows, closings)`,
      },
      {
        name: 'MSTD',
        fullName: 'Moving Starndard Deviation',
        description: `The mstd function calculates the moving standard deviation for a given period.`,
      },
      {
        name: 'PO',
        fullName: 'Projection Oscillator',
        description: `The projectionOscillator calculates the Projection Oscillator (PO). The PO uses the linear regression slope, along with highs and lows.Period defines the moving window to calculates the PO, and the smooth period defines the moving windows to take EMA of PO.

PL = Min(period, (high + MLS(period, x, high)))
PU = Max(period, (low + MLS(period, x, low)))
PO = 100 * (Closing - PL) / (PU - PL)
SPO = EMA(smooth, PO)`,
        strategyName: 'PO',
      },
      {
        name: 'TR',
        fullName: 'True Range',
        description: `The trueRange function calculates the True Range (TR) for a given period.

TR = Max((High - Low), Abs(High - Closing[-1]), Abs(Low - Closing[-1]))`,
      },
      {
        name: 'UI',
        fullName: 'Ulcer Index',
        description: `The ulcerIndex measures downside risk. The index increases in value as the price moves farther away from a recent high and falls as the price rises to new highs.

High Closings = Max(period, Closings)
Percentage Drawdown = 100 * ((Closings - High Closings) / High Closings)
Squared Average = Sma(period, Percent Drawdown * Percent Drawdown)
Ulcer Index = Sqrt(Squared Average)`,
      },
    ],
  },
  {
    category: 'Volume',
    items: [
      {
        name: 'A/D',
        fullName: 'accumulationDistribution',
        description: `The accumulationDistribution is a cumulative indicator that uses volume and price to assess whether a stock is being accumulated or distributed. The Accumulation/Distribution seeks to identify divergences between the stock price and the volume flow.

MFM = ((Closing - Low) - (High - Closing)) / (High - Low)
MFV = MFM * Period Volume
AD = Previous AD + CMFV`,
      },
      {
        name: 'CMF',
        fullName: 'Chaikin Money Flow',
        description: `The chaikinMoneyFlow measures the amount of money flow volume over a given period.

Money Flow Multiplier = ((Closing - Low) - (High - Closing)) / (High - Low)
Money Flow Volume = Money Flow Multiplier * Volume
Chaikin Money Flow = Sum(20, Money Flow Volume) / Sum(20, Volume)`,
        strategyName: 'CMF',
      },
      {
        name: 'EMV',
        fullName: 'Ease of Movement',
        description: `The easeOfMovement is a volume based oscillator measuring the ease of price movement.

Distance Moved = ((High + Low) / 2) - ((Priod High + Prior Low) /2)
Box Ratio = ((Volume / 100000000) / (High - Low))
EMV(1) = Distance Moved / Box Ratio
EMV(14) = SMA(14, EMV(1))`,
        strategyName: 'EMV',
      },
      {
        name: 'FI',
        fullName: 'ForceIndex',
        description: `The forceIndex uses the closing price and the volume to assess the power behind a move and identify turning points.

Force Index = EMA(period, (Current - Previous) * Volume)`,
        strategyName: 'FI',
      },
      {
        name: 'MFI',
        fullName: 'MoneyFlowIndex',
        description: `The moneyFlowIndex function analyzes both the closing price and the volume to measure to identify overbought and oversold states. It is similar to the Relative Strength Index (RSI), but it also uses the volume.

Raw Money Flow = Typical Price * Volume
Money Ratio = Positive Money Flow / Negative Money Flow
Money Flow Index = 100 - (100 / (1 + Money Ratio))`,
        strategyName: 'MFI',
      },
      {
        name: 'NVI',
        fullName: 'NegativeVolumeIndex',
        description: `The negativeVolumeIndex function calculates a cumulative indicator using the change in volume to decide when the smart money is active.

If Volume is greather than Previous Volume:
NVI = Previous NVI
Otherwise:
NVI = Previous NVI + (((Closing - Previous Closing) / Previous Closing) * Previous NVI)`,
        strategyName: 'NVI',
      },
      {
        name: 'OBV',
        fullName: 'On-Balance Volume',
        description: `The onBalanceVolume function calculates a technical trading momentum indicator that uses volume flow to predict changes in stock price.

OBV = OBV - volume, if Closing > Closing-Prev
OBV = OBV - Prev + 0, if Closing = Closing-Prev
OBV = OBV - volume, if Closing < Closing-Prev`,
      },
      {
        name: 'VPT',
        fullName: 'VolumePriceTrend',
        description: `The volumePriceTrend provides a correlation between the volume and the price.

VPT = Previous VPT + (Volume * (Current Closing - Previous Closing) / Previous Closing)`,
      },
      {
        name: 'VWAP',
        fullName: 'VolumeWeightedAveragePrice',
        description: `The volumeWeightedAveragePrice provides the average price the asset has traded.

VWAP = Sum(Closing * Volume) / Sum(Volume)`,
        strategyName: 'VWAP',
      },
    ],
  },
]
export const QuotesItems: ItemsProps[] = [
  {
    category: 'NewVersion',
    items: [
      { name: '1 D' },
      { name: '5 D' },
      { name: '1 M' },
      { name: '6 M' },
      { name: 'YTD' },
      { name: '1 Y' },
      { name: '5 Y' },
    ],
  },
]

export const menuButtonCls = clsx(
  'set-ring-1 inset-ring-white/5 inline-flex w-full justify-center gap-x-1.5 rounded-md px-3 py-2',
  'dark:bg-white/10 underline md:no-underline text-sm font-semibold text-black dark:text-white hover:bg-white/20'
)
export const menuItemsClsQuotes = clsx(
  'hidden data-[headlessui-state~=open]:block',
  'data-closed:scale-95 data-closed:transform data-closed:opacity-0',
  'data-enter:duration-100 data-enter:ease-out',
  'data-leave:duration-75 data-leave:ease-in',
  'fixed top-1/2 md:absolute md:left-0 md:transform',
  'z-10 mt-2 max-w-1xl w-[fit-content(100%)] origin-top-right divide-y divide-white/10 rounded-md bg-blue-500 outline-1 -outline-offset-1 outline-white/10 transition'
)
export const menuItemsClsIndicators = clsx(
  'hidden data-[headlessui-state~=open]:block',
  'data-closed:scale-95 data-closed:transform data-closed:opacity-0',
  'data-enter:duration-100 data-enter:ease-out',
  'data-leave:duration-75 data-leave:ease-in',
  'fixed md:absolute left-1/2 top-1/2 -translate-x-1/4 -translate-y-1/4 md:transform',
  'z-10 mt-2 w-[fit-content(100%)] origin-top-right divide-y divide-white/10 rounded-md bg-blue-500 outline-1 -outline-offset-1 outline-white/10 transition'
)
export const menuItemsClsStrategies = clsx(
  'hidden data-[headlessui-state~=open]:block',
  'data-closed:scale-95 data-closed:transform data-closed:opacity-0',
  'data-enter:duration-100 data-enter:ease-out',
  'data-leave:duration-75 data-leave:ease-in',
  'fixed md:absolute left-1/2 top-1/2 md:transform',
  'z-10 mt-2 w-[fit-content(100%)] origin-top-right divide-y divide-white/10 rounded-md bg-blue-500 outline-1 -outline-offset-1 outline-white/10 transition'
)
export const menuItemClass = clsx(
  `flex-shrink-0 snap-center rounded-md px-4 py-2`,
  `font-bold text-left md:text-center text-sm text-white`,
  `w-[fit-content(100%)]`,
  `bg-blue-500 hover:bg-blue-700`,
  `md:text-base md:bg-blue-500 md:text-white md:hover:bg-blue-700`
)

export const menuItemClassHighlight = clsx(
  `flex-shrink-0 snap-center rounded-md px-4 py-2`,
  `font-bold text-left md:text-center text-sm text-white`,
  `border border-2 border-white p-2`,
  `w-[fit-content(100%)]`,
  `bg-blue-500 hover:bg-blue-700`,
  `md:text-base md:bg-blue-500 md:text-white md:hover:bg-blue-700`
)

export interface AnnotationLabel {
  borderColor?: string
  borderWidth?: number
  borderRadius?: number
  text?: string | string[]
  textAnchor?: string
  offsetX?: number
  offsetY?: number
  style?: AnnotationStyle
  position?: string
  orientation?: string
  mouseEnter?: (event) => void
  mouseLeave?: (event) => void
  click?: (event) => void
}

export interface XAxisAnnotations {
  id?: number | string
  x?: null | number | string
  x2?: null | number | string
  strokeDashArray?: number
  fillColor?: string
  borderColor?: string
  borderWidth?: number
  opacity?: number
  offsetX?: number
  offsetY?: number
  label?: AnnotationLabel
}

export interface YAxisAnnotations {
  id?: number | string
  y?: null | number | string
  y2?: null | number | string
  strokeDashArray?: number
  fillColor?: string
  borderColor?: string
  borderWidth?: number
  opacity?: number
  offsetX?: number
  offsetY?: number
  width?: number | string
  yAxisIndex?: number
  label?: AnnotationLabel
}

export interface PointAnnotationsMarker {
  size?: number
  fillColor?: string
  strokeColor?: string
  strokeWidth?: number
  shape?: string
  offsetX?: number
  offsetY?: number
  cssClass?: string
}
export interface PointAnnotations {
  id?: number | string
  x?: number | string
  y?: null | number
  yAxisIndex?: number
  seriesIndex?: number
  mouseEnter?: (event) => void
  mouseLeave?: (event) => void
  click?: (event) => void
  marker?: PointAnnotationsMarker
  label?: AnnotationLabel
  image?: {
    path?: string
    width?: number
    height?: number
    offsetX?: number
    offsetY?: number
  }
}

export interface TextAnnotations {
  x?: number
  y?: number
  text?: string
  textAnchor?: string
  foreColor?: string
  fontSize?: string | number
  fontFamily?: undefined | string
  fontWeight?: string | number
  backgroundColor?: string
  borderColor?: string
  borderRadius?: number
  borderWidth?: number
  paddingLeft?: number
  paddingRight?: number
  paddingTop?: number
  paddingBottom?: number
}

export interface ImageAnnotations {
  path?: string
  x?: number
  y?: number
  width?: number
  height?: number
}

export interface ApexAnnotations {
  yaxis?: YAxisAnnotations[]
  xaxis?: XAxisAnnotations[]
  points?: PointAnnotations[]
  texts?: TextAnnotations[]
  images?: ImageAnnotations[]
}

export interface ApexAxisChartSeries {
  name?: string
  type?: string
  color?: string
  group?: string
  hidden?: boolean
  zIndex?: number
  parsing?: ApexParsing
  data:
    | (number | null)[]
    | {
        x: unknown
        y: unknown
        fill?: ApexFill
        fillColor?: string
        strokeColor?: string
        meta?: unknown
        goals?: {
          name?: string
          value: number
          strokeHeight?: number
          strokeWidth?: number
          strokeColor?: string
          strokeDashArray?: number
          strokeLineCap?: 'butt' | 'square' | 'round'
        }[]
        barHeightOffset?: number
        columnWidthOffset?: number
      }[]
    | [number, number | null][]
    | [number, (number | null)[]][]
    | number[][]
    | Record<string, unknown>[]
}
export interface ApexYAxis {
  show?: boolean
  showAlways?: boolean
  showForNullSeries?: boolean
  seriesName?: string | string[]
  opposite?: boolean
  reversed?: boolean
  logarithmic?: boolean
  logBase?: number
  tickAmount?: number
  stepSize?: number
  forceNiceScale?: boolean
  min?: number | ((min: number) => number)
  max?: number | ((max: number) => number)
  floating?: boolean
  decimalsInFloat?: number
  labels?: {
    show?: boolean
    showDuplicates?: boolean
    minWidth?: number
    maxWidth?: number
    offsetX?: number
    offsetY?: number
    rotate?: number
    align?: 'left' | 'center' | 'right'
    padding?: number
    style?: {
      colors?: string | string[]
      fontSize?: string
      fontWeight?: string | number
      fontFamily?: string
      cssClass?: string
    }
    formatter?(val: number, opts?: unknown): string | string[]
  }
  axisBorder?: {
    show?: boolean
    color?: string
    width?: number
    offsetX?: number
    offsetY?: number
  }
  axisTicks?: {
    show?: boolean
    color?: string
    width?: number
    offsetX?: number
    offsetY?: number
  }
  title?: {
    text?: string
    rotate?: number
    offsetX?: number
    offsetY?: number
    style?: {
      color?: string
      fontSize?: string
      fontWeight?: string | number
      fontFamily?: string
      cssClass?: string
    }
  }
  crosshairs?: {
    show?: boolean
    position?: string
    stroke?: {
      color?: string
      width?: number
      dashArray?: number
    }
  }
  tooltip?: {
    enabled?: boolean
    offsetX?: number
  }
}
export interface ApexXAxis {
  type?: 'category' | 'datetime' | 'numeric'
  categories?: number[] | string[]
  overwriteCategories?: number[] | string[] | undefined
  offsetX?: number
  offsetY?: number
  sorted?: boolean
  labels?: {
    show?: boolean
    rotate?: number
    rotateAlways?: boolean
    hideOverlappingLabels?: boolean
    showDuplicates?: boolean
    trim?: boolean
    minHeight?: number
    maxHeight?: number
    style?: {
      colors?: string | string[]
      fontSize?: string
      fontFamily?: string
      fontWeight?: string | number
      cssClass?: string
    }
    offsetX?: number
    offsetY?: number
    format?: string
    formatter?(value: string | number, timestamp?: number, opts?: undefined): string | string[]
    datetimeUTC?: boolean
    datetimeFormatter?: {
      year?: string
      month?: string
      day?: string
      hour?: string
      minute?: string
      second?: string
    }
  }
  group?: {
    groups?: { title: string; cols: number }[]
    style?: {
      colors?: string | string[]
      fontSize?: string
      fontFamily?: string
      fontWeight?: string | number
      cssClass?: string
    }
  }
  axisBorder?: {
    show?: boolean
    color?: string
    height?: number
    offsetX?: number
    offsetY?: number
  }
  axisTicks?: {
    show?: boolean
    borderType?: string
    color?: string
    height?: number
    offsetX?: number
    offsetY?: number
  }
  tickPlacement?: string
  tickAmount?: number | 'dataPoints'
  stepSize?: number
  min?: number
  max?: number
  range?: number
  floating?: boolean
  decimalsInFloat?: number
  position?: string
  title?: {
    text?: string
    offsetX?: number
    offsetY?: number
    style?: {
      color?: string
      fontFamily?: string
      fontWeight?: string | number
      fontSize?: string
      cssClass?: string
    }
  }
  crosshairs?: {
    show?: boolean
    width?: number | string
    position?: string
    opacity?: number
    stroke?: {
      color?: string
      width?: number
      dashArray?: number
    }
    fill?: {
      type?: string
      color?: string
      gradient?: {
        colorFrom?: string
        colorTo?: string
        stops?: number[]
        opacityFrom?: number
        opacityTo?: number
      }
    }
    dropShadow?: ApexDropShadow
  }
  tooltip?: {
    enabled?: boolean
    offsetY?: number
    formatter?(value: string | number, opts?: object): string
    style?: {
      fontSize?: string
      fontFamily?: string
    }
  }
}
